import './globals.css'
import { Inter } from 'next/font/google'
import AuthProvider from '@/app/providers/AuthProvider'
import ThemeProvider, {
  getPaletteFromLS,
} from '@/app/providers/MuiThemeProvider'
import AdaptiveBackground from '@/components/AdaptiveBackground'
import StylableClerkProvider from '@/app/providers/StylableClerkProvider'
import Header from '@/components/header'
import ReactQueryProvider from './providers/ReactQueryProvider'
import { ClientChakraProvider } from './providers/ClientChakraProvider'
import { FilterProvider } from './providers/FilterProvider'
import MuiThemeProvider from '@/app/providers/MuiThemeProvider'
import { DialogProvider } from './providers/DialogProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <MuiThemeProvider>
      <ReactQueryProvider>
        <StylableClerkProvider>
          <AuthProvider>
            <html lang="en">
              <DialogProvider>
                <body className={inter.className}>
                  <FilterProvider>
                    <ClientChakraProvider>
                      <div className="flex flex-col h-screen">
                        <Header />
                        <AdaptiveBackground>{children}</AdaptiveBackground>
                      </div>
                    </ClientChakraProvider>
                  </FilterProvider>
                </body>
              </DialogProvider>
            </html>
          </AuthProvider>
        </StylableClerkProvider>
      </ReactQueryProvider>
    </MuiThemeProvider>
  )
}
