import './globals.css'
import { Inter } from 'next/font/google'
import AuthProvider from '@/app/providers/AuthProvider'
import ThemeProvider, { getPaletteFromLS } from '@/app/providers/ThemeProvider'
import AdaptiveBackground from '@/components/AdaptiveBackground'
import StylableClerkProvider from '@/app/providers/StylableClerkProvider'
import { ClerkProvider } from '@clerk/nextjs'
import Header from '@/components/header'
import { dark } from '@clerk/themes'
import { useRouter } from 'next/navigation'
import { ClientClerkProvider } from '@clerk/nextjs/dist/app-router/client/ClerkProvider'
import ReactQueryProvider from './providers/ReactQueryProvider'
import { ClientChakraProvider } from './providers/ChakraProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ThemeProvider>
      <ReactQueryProvider>
        <StylableClerkProvider>
            <html lang="en">
              <body className={inter.className}>
                <ClientChakraProvider>
                  <Header />
                  <AdaptiveBackground>{children}</AdaptiveBackground>
                </ClientChakraProvider>
              </body>
            </html>
        </StylableClerkProvider>
      </ReactQueryProvider>
    </ThemeProvider>
  )
}
